import {actionState,verificationState} from './ui-motion.js';
import {setupDialogHTML} from './setup-dialog.js';
import {tr, registerMessages} from './product-ui.js';
registerMessages({'More metrics':'更多指标','Fewer metrics':'收起指标','Menu':'菜单','Settings':'设置','Website setup':'网站接入','Manage connection':'管理连接','1 · Website':'1 · 网站','2 · Install':'2 · 安装','3 · Verify':'3 · 验证','Your website':'你的网站','Website URL':'网站链接','Website ID':'网站 ID','How would you like to connect?':'选择接入方式','Agent + Skill (recommended)':'Agent + Skill（默认推荐）','Set up manually':'手动接入','Continue →':'继续 →','Give your agent the setup task':'把接入任务交给 Agent','Copy agent task':'复制 Agent 指令','Read Skill ↗':'查看 Skill ↗','Install the tracker manually':'手动安装追踪代码','Check your connection':'检查连接','Check connection →':'检查连接 →','Verify a real visit':'验证一次真实访问','Open your website ↗':'打开你的网站 ↗','Check for pageview':'检查页面访问','Open dashboard →':'打开仪表盘 →','Back':'返回','Not receiving data?':'没有收到数据？','Use manual setup':'改用手动接入','Use Agent + Skill':'改用 Agent + Skill','Checking…':'检查中…','Copied':'已复制','Copy failed. Select and copy the task below.':'复制失败，请选中下方指令手动复制。','Waiting for a new pageview. Visit your website, then check again.':'等待新的页面访问。请访问网站后再检查。','Pageview received. Website setup verified.':'已收到页面访问，网站接入验证通过。','Website setup complete':'网站接入已完成','Continue website setup':'继续网站接入','Connection verified. Now visit your website.':'连接已验证，请现在访问你的网站。','Use your coding agent to configure your website, or follow the manual guide.':'让编程 Agent 配置你的网站，或按手动指南完成。','Open the agent in your website project. Copy this task to let it read the Skill and prepare the integration.':'在你的网站项目中打开 Agent，复制下面的任务，让它读取 Skill 并准备接入。','When configuration is ready, enter your private dashboard read token. It stays in this browser tab and is never included in the agent task.':'配置就绪后填写私有读取 token。它仅保存在当前浏览器标签页，不会包含在 Agent 指令中。','Open your website, allow tracking through its consent flow, and visit a page. Then check whether TideStat received a new pageview.':'打开你的网站，按网站的同意流程允许追踪并访问页面，然后检查 TideStat 是否收到新的访问事件。'});
registerMessages({"Finish connecting your website": "完成网站接入", "Use Agent + Skill by default, or follow the manual steps. Verify a real pageview before finishing.": "默认由 Agent 按 Skill 接入，也可选择手动配置。收到真实页面访问后完成验证。", "Manual snippet & site details": "手动代码与网站详情", "Plans & billing": "套餐与账单", "Your signed-in account authorizes this check. No read token is needed.": "使用当前登录账户验证，无需填写读取 token。", "Configure the website origin and private read token in SITES_JSON, then install the Browser SDK using your site's consent flow.": "在 SITES_JSON 中配置网站来源及私有读取 token，然后按网站的同意流程安装 Browser SDK。", "1. Configure website ↗": "1. 配置网站 ↗", "2. Install Browser SDK ↗": "2. 安装 Browser SDK ↗", "The tracker starts with consent disabled. Call window.tidestat.setConsent(true) only after your site's consent flow permits tracking.": "追踪代码默认不采集数据。请在网站的同意流程允许后调用 window.tidestat.setConsent(true)。", "Check the exact allowed origin, matching website ID, consent, browser blockers, and the /api/collect response in your website's network panel. Payment connectors are optional and have separate verification.": "检查网站来源是否匹配、网站 ID、同意状态、浏览器拦截器，以及网络面板中的 /api/collect 响应。支付接入为可选项，需单独验证。", "Check the website ID and read token in your server configuration.": "请检查服务器配置中的网站 ID 和读取 token。", "This website origin is not allowed. Update SITES_JSON with the exact website origin and retry.": "网站来源不匹配，请核对注册的网站域名或 SITES_JSON 配置后重试。", "Enter an HTTP or HTTPS website URL without credentials.": "请输入不含登录凭证的 HTTP 或 HTTPS 网站链接。"});
registerMessages({'Review website setup':'查看接入记录','Your website is registered. Install the Browser SDK using your existing consent flow.':'网站已注册，请按现有同意流程安装 Browser SDK。'});
registerMessages({'Copying…':'复制中…','Copy again':'再次复制','Try again':'重试','Check again':'再次检查','Connection verified':'连接已验证','Checking for a new pageview…':'正在检查新的页面访问…','Received at {time}':'收到时间：{time}','Agent task copied.':'Agent 指令已复制。'});
registerMessages({"Install Skill in your project": "安装 Skill 到网站项目", "Download SKILL.md": "下载 SKILL.md", "Download the Skill and save it as .agents/skills/tidestat-connect/SKILL.md in your website project. Ask your agent to read that file and follow the setup task above. If your agent cannot open links, this local file provides the same instructions.": "下载 Skill，保存到网站项目的 .agents/skills/tidestat-connect/SKILL.md。让 Agent 读取该文件并执行上方接入任务。Agent 无法打开链接时，也可以通过此本地文件读取完整指引。", "Reading or installing the Skill does not connect your website. The agent must make the changes, then verify a real visit.": "读取或安装 Skill 不代表接入完成。Agent 需要实际修改网站，再验证一次真实访问。", "Install from a local SDK package": "通过本地 SDK 软件包安装", "In your website project, replace the path below with your local TideStat repository path. The SDK is not published to npm.": "在你的网站项目中执行，将下面的路径替换为本地 TideStat 仓库路径。SDK 尚未发布到 npm。", "Without a local repository, use the hosted script below. Your build environment must also have access to any local package path.": "没有本地仓库时，使用下方托管脚本。使用本地软件包时，构建环境也必须能访问该路径。"});
const $=id=>document.getElementById(id);
export function initOnboarding({onConnected,onDisconnect}){
 if(!$('connectDialog'))document.body.insertAdjacentHTML('beforeend',setupDialogHTML);
 let state={step:1,method:'agent'},revision=0,copyTimer;
 const operations=new WeakMap();
 const announcement=document.createElement('p');announcement.id='setupActionStatus';announcement.className='product-sr-only';announcement.setAttribute('role','status');$('connectDialog').append(announcement);
 try{const saved=JSON.parse(sessionStorage.getItem('tidestat.setup')||'null');if(saved&&[1,2,3].includes(saved.step))state=saved;}catch{}
 const save=()=>{sessionStorage.setItem('tidestat.setup',JSON.stringify(state));if(state.site)sessionStorage.setItem('tidestat.setup.'+state.site,JSON.stringify(state));};
 function render(){
  $('websiteForm').hidden=state.step!==1;$('installStep').hidden=state.step!==2;$('verifyStep').hidden=state.step!==3;
  document.querySelectorAll('[data-step]').forEach(el=>{if(Number(el.dataset.step)===state.step)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');});
  $('websiteForm').elements.url.value=state.origin||'';$('websiteForm').elements.site.value=state.site||window.tideConnection.get().site||'';$('websiteForm').elements.method.value=state.method;
  $('connectForm').elements.site.value=state.site||'';
  const token=$('connectForm').elements.token;token.required=!state.sessionMode;token.closest('label').hidden=!!state.sessionMode;$('sessionSetupNote').hidden=!state.sessionMode;$('connectForm').querySelectorAll('p:not(#sessionSetupNote)').forEach(p=>p.hidden=!!state.sessionMode);
  $('agentGuide').hidden=state.method!=='agent';$('manualGuide').hidden=state.method!=='manual';$('switchMethod').textContent=tr(state.method==='agent'?'Use manual setup':'Use Agent + Skill');
  $('agentTask').value=`Read and follow ${location.origin}/docs/tidestat-connect/SKILL.md. Connect my website ${state.origin||''} to TideStat at ${location.origin} using site ID ${state.site||''}. Inspect this website project, ${state.sessionMode?'The website is already registered in my TideStat account; preserve its website ID and allowed origin.':'Configure its allowed origin.'} The Browser SDK is unpublished: do not run npm install @tidestat/browser-sdk. If a local TideStat repository is available, locate packages/browser-sdk and install it by its quoted absolute filesystem path from this website project; ensure the build environment can access that path. Otherwise use the hosted SDK at ${location.origin}/sdk/browser.js (or /sdk/index.js) without a registry install. Integrate the SDK with existing consent, and verify a real pageview. Preserve other websites and existing changes. Keep read tokens and webhook secrets out of client code, chat, and commits. Prepare changes and request any required deployment authorization. Report changed files and verification evidence; do not claim completion from credentials alone.`;
  $('manualSnippet').textContent=`<script type="module" src="${location.origin}/sdk/browser.js" data-site="${state.site||''}" data-consent="false"></script>`;
  $('manualGuide').querySelector('a[href*=sites]').hidden=!!state.sessionMode;
  $('manualGuide').querySelector('p').textContent=tr(state.sessionMode?'Your website is registered. Install the Browser SDK using your existing consent flow.':'Configure the website origin and private read token in SITES_JSON, then install the Browser SDK using your site\'s consent flow.');
  $('disconnect').hidden=!!state.sessionMode;
  $('visitWebsite').href=state.origin||'#';$('finishSetup').hidden=!state.verified;$('verifyVisit').hidden=!!state.verified;
  if($('setupProgress'))$('setupProgress').textContent=tr(state.site===window.tideConnection.get().site&&state.verified?'Website setup complete':state.step>1?'Continue website setup':'Website setup');
 }
 function resetActions(){for(const button of [$('copyAgent'),$('connectForm').querySelector('[type=submit]'),$('verifyVisit')]){operations.delete(button);button.disabled=false;}clearTimeout(copyTimer);announcement.textContent='';actionState($('copyAgent'),'idle','Copy agent task');actionState($('connectForm').querySelector('[type=submit]'),'idle','Check connection →');actionState($('verifyVisit'),'idle','Check for pageview');}
 function move(step){revision++;state.step=step;$('setupError').textContent='';save();render();resetActions();}
 $('connectDialog').addEventListener('close',()=>{revision++;});
 if($('moreMetrics'))$('moreMetrics').onclick=()=>{const open=$('moreMetrics').getAttribute('aria-expanded')!=='true';$('moreMetrics').setAttribute('aria-expanded',String(open));$('metrics').classList.toggle('expanded',open);$('moreMetrics').textContent=tr(open?'Fewer metrics':'More metrics');};
 if($('mobileMenu'))$('mobileMenu').onclick=()=>{const open=$('mobileMenu').getAttribute('aria-expanded')!=='true';$('mobileMenu').setAttribute('aria-expanded',String(open));document.querySelector('.sidebar').classList.toggle('menu-open',open);};
 document.querySelectorAll('#productNavigation a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('.sidebar').classList.remove('menu-open');$('mobileMenu').setAttribute('aria-expanded','false');}));
 for(const id of ['setupProgress','manageConnection'])if($(id))$(id).onclick=()=>{if(id==='setupProgress'){const c=window.tideConnection.get(),site=c.sites?.find(s=>s.id===c.site);if(c.session&&site)return begin(site);}revision++;if(id==='manageConnection')state={step:1,method:'agent'};render();resetActions();$('connectDialog').showModal();};
 $('websiteForm').onsubmit=e=>{e.preventDefault();const f=e.target.elements;let url;try{url=new URL(f.url.value);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error();}catch{$('setupError').textContent='Enter an HTTP or HTTPS website URL without credentials.';return;}state={step:2,origin:url.origin,site:f.site.value.trim(),method:f.method.value,verified:false};move(2);};
 $('switchMethod').onclick=()=>{state.method=state.method==='agent'?'manual':'agent';save();render();};
 $('backWebsite').onclick=()=>{if(state.sessionMode){$('connectDialog').close();return;}move(1);};$('backInstall').onclick=()=>{state.verified=false;move(2);};
 $('copyAgent').onclick=async()=>{const ticket=revision;clearTimeout(copyTimer);const button=$('copyAgent'),operation={};operations.set(button,operation);button.disabled=true;actionState(button,'pending','Copying…');try{await navigator.clipboard.writeText($('agentTask').value);if(ticket!==revision)return;actionState(button,'success','Copied');announcement.textContent=tr('Agent task copied.');copyTimer=setTimeout(()=>actionState(button,'idle','Copy agent task'),2400);}catch{if(ticket!==revision)return;actionState(button,'error','Copy again');$('setupError').textContent=tr('Copy failed. Select and copy the task below.');$('agentTask').select();}finally{if(operations.get(button)===operation){button.disabled=false;if(ticket!==revision)actionState(button,'idle','Copy agent task');}}};
 async function check(token,since){const url=new URL('/api/setup',location.origin);url.searchParams.set('site',state.site);url.searchParams.set('origin',state.origin);url.searchParams.set('since',since);const r=await fetch(url,{headers:token?{Authorization:`Bearer ${token}`}:{},credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(state.sessionMode&&r.status===401?'Sign in again to continue.':r.status===401||r.status===400?'Check the website ID and read token in your server configuration.':`Connection check unavailable (${r.status}). Retry after deploying the updated Worker.`);const result=await r.json();if(result.site!==state.site||typeof result.pageviewReceived!=='boolean')throw Error('Unexpected verification response.');if(!result.originAllowed)throw Error('This website origin is not allowed. Update SITES_JSON with the exact website origin and retry.');return result;}
 async function run(button,task){
  const operation={},ticket=revision;operations.set(button,operation);button.disabled=true;actionState(button,'pending','Checking…');$('setupError').textContent='';
  if(button.id==='verifyVisit')verificationState($('verifyResult'),'pending','Checking for a new pageview…');
  try{const outcome=await task();if(operations.get(button)!==operation||outcome==='stale')return;actionState(button,outcome==='waiting'?'waiting':'success',outcome==='waiting'?'Check again':button.id==='verifyVisit'?'Website setup complete':'Connection verified');}
  catch(error){if(ticket!==revision)return;const message=error.name==='TimeoutError'?'The check timed out. Please retry.':error.message;$('setupError').textContent=message;actionState(button,'error','Try again');if(button.id==='verifyVisit')verificationState($('verifyResult'),'error',message);}
  finally{if(operations.get(button)===operation){button.disabled=false;button.setAttribute('aria-busy','false');}}
 }
 $('connectForm').onsubmit=e=>{e.preventDefault();const ticket=revision,token=state.sessionMode?'':e.target.elements.token.value.trim();run(e.submitter,async()=>{await check(token,Date.now());if(ticket!==revision)return 'stale';if(!state.sessionMode)window.tideConnection.set(state.site,token);state.since=Date.now();state.verified=false;verificationState($('verifyResult'),'waiting','Connection verified. Now visit your website.');move(3);onConnected();return 'success';});};
 $('verifyVisit').onclick=()=>{const ticket=revision;run($('verifyVisit'),async()=>{const c=window.tideConnection.get();if(c.site!==state.site||(!c.token&&!c.session))throw Error('Reconnect this website before verification.');const result=await check(state.sessionMode?'':c.token,state.since||Date.now());if(ticket!==revision)return 'stale';state.verified=result.pageviewReceived;state.verifiedAt=result.lastPageviewAt;verificationState($('verifyResult'),state.verified?'success':'waiting',state.verified?'Pageview received. Website setup verified.':'Waiting for a new pageview. Visit your website, then check again.',state.verifiedAt);save();render();return state.verified?'success':'waiting';});};
 $('finishSetup').onclick=()=>{$('connectDialog').close();if(document.querySelector('.account-main')){location.href='./revenue.html';return;}location.hash='overview';onConnected();};
 $('disconnect').onclick=()=>{revision++;window.tideConnection.clear();sessionStorage.removeItem('tidestat.setup');state={step:1,method:'agent'};$('connectForm').reset();$('setupError').textContent='';$('verifyResult').textContent='';render();$('connectDialog').close();onDisconnect();};
 function begin(site){revision++;let saved;try{saved=JSON.parse(sessionStorage.getItem('tidestat.setup.'+site.id)||'null');}catch{}state=saved?.origin===site.origin?{...saved,sessionMode:true}:{step:2,method:'agent',site:site.id,origin:site.origin,sessionMode:true};$('setupError').textContent='';if(state.step===3)verificationState($('verifyResult'),state.verified?'success':'waiting',state.verified?'Pageview received. Website setup verified.':'Waiting for a new pageview. Visit your website, then check again.',state.verifiedAt);else{$('verifyResult').textContent='';delete $('verifyResult').dataset.status;}save();render();resetActions();$('connectDialog').showModal();}
 if($('connectionButton'))$('connectionButton').onclick=()=>{revision++;state={step:1,method:'agent'};render();resetActions();$('connectDialog').showModal();};
 for(const button of $('connectDialog').querySelectorAll('[data-close]'))button.onclick=()=>{$('connectDialog').close();};
 window.addEventListener('tide:setup',event=>begin(event.detail));
 render();resetActions();
 return {begin};
}

