export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatMoney=(minor,currency,language='en')=>{try{const digits=new Intl.NumberFormat(language,{style:'currency',currency}).resolvedOptions().maximumFractionDigits;return new Intl.NumberFormat(language,{style:'currency',currency}).format(minor/10**digits);}catch{return `${currency} ${minor} minor units`;}};
export {icon} from './ui-icons.js';
export const brandMark=()=>'<svg class="brand-mark" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M3 19c5 0 5-9 10-9s5 12 10 12 5-9 6-9M3 25c5 0 5-9 10-9s5 12 10 12 5-9 6-9" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>';
export function trendSVG(rows=[],metric='visitors',currency='USD') {
 if(!rows.length)return '<div class="chart-empty">Daily activity will appear after your first tracked visit.</div>';
 const light=globalThis.document?.documentElement.dataset.theme==='light',accent=light?'#b64d2a':'#ed916f',ink=light?'#526d60':'#b8cdc5',grid=light?'#dce4df':'#31393c',muted=light?'#687870':'#829095',bg=light?'#f8f9f6':'#121719';
 const values=rows.map(r=>metric==='revenue'?Number(r.revenue?.[currency]||0):Number(r.visitors||0)),max=Math.max(1,...values),min=Math.min(0,...values),width=920,height=190,pad=14,range=max-min||1;
 const points=values.map((v,i)=>[pad+i*(width-pad*2)/Math.max(1,values.length-1),height-pad-(v-min)/range*(height-pad*2)]);
 const line=points.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
 return `<svg class="trend-chart" viewBox="0 0 ${width} ${height+30}" role="img" aria-label="Daily ${metric} trend, ${rows.length} days. Minimum ${Math.min(...values)}, maximum ${Math.max(...values)}${metric==='revenue'?' minor currency units':''}."><defs><linearGradient id="trendFill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${metric==='revenue'?accent:ink}" stop-opacity=".22"/><stop offset="1" stop-color="${bg}" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map(i=>`<path d="M0 ${pad+i*(height-pad*2)/3}H${width}" stroke="${grid}" stroke-dasharray="3 6"/>`).join('')}<path d="${line} L${points.at(-1)[0]},${height} L${points[0][0]},${height}Z" fill="url(#trendFill)"/><path d="${line}" fill="none" stroke="${metric==='revenue'?accent:ink}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>${points.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="4" fill="transparent"><title>${escapeHTML(rows[i].date)}: ${metric==='revenue'?escapeHTML(formatMoney(values[i],currency)):values[i]}</title></circle>`).join('')}<text x="0" y="${height+24}" fill="${muted}" font-size="11">${escapeHTML(rows[0].date)}</text><text text-anchor="end" x="${width}" y="${height+24}" fill="${muted}" font-size="11">${escapeHTML(rows.at(-1).date)}</text></svg>`;
}
export function exportSVG({site,range,currency,total,visitors,sessions,conversion,rows=[],journey='',sample=false,language='en',light=false,labels={}}) {
 const safe=escapeHTML,ink=light?'#25332d':'#f0f3f2',bg=light?'#f8f9f6':'#121719',accent=light?'#b64d2a':'#ed916f',muted=light?'#65736c':'#a1adad',max=Math.max(1,...rows.map(r=>Number(r.revenue?.[currency]||0)));
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720" viewBox="0 0 1200 720"><rect width="1200" height="720" fill="${bg}"/><g font-family="Arial,sans-serif" fill="${ink}"><text x="64" y="70" font-size="26" font-weight="bold">TideStat</text><text x="1136" y="70" text-anchor="end" font-size="15" fill="${muted}">${sample?safe(labels.sample||'SAMPLE DATA · ILLUSTRATIVE'):safe(range)}</text><text x="64" y="146" font-size="18" fill="${muted}">${safe(site)} · ${safe(labels.snapshot||'Revenue snapshot')}</text><text x="64" y="224" font-size="66" fill="${accent}">${safe(total)}</text><text x="66" y="255" font-size="15" fill="${muted}">${safe(labels.net||'Net recorded revenue')} · ${safe(currency)}</text>${[[visitors,labels.visitors||'Visitors'],[sessions,labels.sessions||'Sessions'],[conversion,labels.conversion||'Conversion']].map(([v,l],i)=>`<text x="${680+i*160}" y="195" font-size="30">${safe(v)}</text><text x="${680+i*160}" y="226" font-size="14" fill="${muted}">${safe(l)}</text>`).join('')}<path d="M64 300H1136" stroke="#354045"/><text x="64" y="344" font-size="19">${safe(labels.sources||'Revenue sources')}</text>${rows.slice(0,5).map((r,i)=>`<rect x="64" y="${365+i*48}" width="${Math.max(2,Number(r.revenue?.[currency]||0)/max*850)}" height="33" rx="4" fill="${accent}" opacity=".18"/><text x="77" y="${387+i*48}" font-size="15">${safe(r.name)}</text><text x="1136" y="${387+i*48}" text-anchor="end" font-size="15" fill="${accent}">${safe(formatMoney(r.revenue?.[currency]||0,currency,language))}</text>`).join('')}${journey?`<text x="64" y="626" fill="${muted}" font-size="13">${safe(labels.journey||'Leading observed trail')}: ${safe(journey.length>94?journey.slice(0,91)+'…':journey)}</text>`:''}<text x="64" y="670" fill="#829095" font-size="13">${safe(labels.footer||'See the story behind every dollar. · Observed attribution, not proof of causation.')}</text></g></svg>`;
}
