export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatMoney=(minor,currency,language='en')=>{try{const digits=new Intl.NumberFormat(language,{style:'currency',currency}).resolvedOptions().maximumFractionDigits;return new Intl.NumberFormat(language,{style:'currency',currency}).format(minor/10**digits);}catch{return `${currency} ${minor} minor units`;}};
export {icon} from './ui-icons.js';
export const brandMark=()=>'<svg class="brand-mark" viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M3 19c5 0 5-9 10-9s5 12 10 12 5-9 6-9M3 25c5 0 5-9 10-9s5 12 10 12 5-9 6-9" stroke="currentColor" stroke-width="3" stroke-linecap="round"/></svg>';
export function trendSVG(rows=[],metric='visitors',currency='USD') {
 if(!rows.length)return '<div class="chart-empty">Daily activity will appear after your first tracked visit.</div>';
 const values=rows.map(r=>metric==='revenue'?Number(r.revenue?.[currency]||0):Number(r.visitors||0)),max=Math.max(1,...values),min=Math.min(0,...values),width=920,height=190,pad=14,range=max-min||1;
 const points=values.map((v,i)=>[pad+i*(width-pad*2)/Math.max(1,values.length-1),height-pad-(v-min)/range*(height-pad*2)]);
 const line=points.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`).join(' ');
 const last=points.at(-1),payload=escapeHTML(JSON.stringify(points.map(([x,y],i)=>({x:+x.toFixed(1),y:+y.toFixed(1),label:rows[i].date,value:metric==='revenue'?formatMoney(values[i],currency):String(values[i])}))));
 const label=`Daily ${metric} trend, ${rows.length} days. Minimum ${Math.min(...values)}, maximum ${Math.max(...values)}${metric==='revenue'?' minor currency units':''}. Drag across the line or use the arrow keys.`;
 return `<div class="tide-plot" data-tide-plot tabindex="0" role="slider" aria-valuemin="0" aria-valuemax="${points.length-1}" aria-valuenow="${points.length-1}" aria-label="${escapeHTML(label)}"><div class="tide-readout"><span data-tide-label>${escapeHTML(rows.at(-1).date)}</span><strong data-no-translate data-tide-value>${escapeHTML(metric==='revenue'?formatMoney(values.at(-1),currency):String(values.at(-1)))}</strong></div><svg class="trend-chart" viewBox="0 0 ${width} ${height+30}" data-points="${payload}"><path class="tide-grid" d="${[0,1,2,3].map(i=>`M0 ${pad+i*(height-pad*2)/3}H${width}`).join('')}"/><path class="tide-area" d="${line} L${last[0].toFixed(1)},${height} L${points[0][0].toFixed(1)},${height}Z"/><path class="tide-line" pathLength="1" d="${line}"/><line class="tide-cross" x1="${last[0].toFixed(1)}" y1="${pad}" x2="${last[0].toFixed(1)}" y2="${height}"/><circle class="tide-cursor" r="4.5" cx="${last[0].toFixed(1)}" cy="${last[1].toFixed(1)}"/><text x="0" y="${height+24}" fill="currentColor" font-size="11">${escapeHTML(rows[0].date)}</text><text text-anchor="end" x="${width}" y="${height+24}" fill="currentColor" font-size="11">${escapeHTML(rows.at(-1).date)}</text></svg></div>`;
}
export function exportSVG({site,range,currency,total,visitors,sessions,conversion,rows=[],journey='',sample=false,language='en',light=false,labels={}}) {
 const safe=escapeHTML,ink=light?'#25332d':'#f0f3f2',bg=light?'#f8f9f6':'#121719',accent=light?'#b64d2a':'#ed916f',muted=light?'#65736c':'#a1adad',max=Math.max(1,...rows.map(r=>Number(r.revenue?.[currency]||0)));
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="720" viewBox="0 0 1200 720"><rect width="1200" height="720" fill="${bg}"/><g font-family="Arial,sans-serif" fill="${ink}"><text x="64" y="70" font-size="26" font-weight="bold">TideStat</text><text x="1136" y="70" text-anchor="end" font-size="15" fill="${muted}">${sample?safe(labels.sample||'SAMPLE DATA · ILLUSTRATIVE'):safe(range)}</text><text x="64" y="146" font-size="18" fill="${muted}">${safe(site)} · ${safe(labels.snapshot||'Revenue snapshot')}</text><text x="64" y="224" font-size="66" fill="${accent}">${safe(total)}</text><text x="66" y="255" font-size="15" fill="${muted}">${safe(labels.net||'Net recorded revenue')} · ${safe(currency)}</text>${[[visitors,labels.visitors||'Visitors'],[sessions,labels.sessions||'Sessions'],[conversion,labels.conversion||'Conversion']].map(([v,l],i)=>`<text x="${680+i*160}" y="195" font-size="30">${safe(v)}</text><text x="${680+i*160}" y="226" font-size="14" fill="${muted}">${safe(l)}</text>`).join('')}<path d="M64 300H1136" stroke="#354045"/><text x="64" y="344" font-size="19">${safe(labels.sources||'Revenue sources')}</text>${rows.slice(0,5).map((r,i)=>`<rect x="64" y="${365+i*48}" width="${Math.max(2,Number(r.revenue?.[currency]||0)/max*850)}" height="33" rx="4" fill="${accent}" opacity=".18"/><text x="77" y="${387+i*48}" font-size="15">${safe(r.name)}</text><text x="1136" y="${387+i*48}" text-anchor="end" font-size="15" fill="${accent}">${safe(formatMoney(r.revenue?.[currency]||0,currency,language))}</text>`).join('')}${journey?`<text x="64" y="626" fill="${muted}" font-size="13">${safe(labels.journey||'Leading observed trail')}: ${safe(journey.length>94?journey.slice(0,91)+'…':journey)}</text>`:''}<text x="64" y="670" fill="#829095" font-size="13">${safe(labels.footer||'See the story behind every dollar. · Observed attribution, not proof of causation.')}</text></g></svg>`;
}
