import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:8894';
const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000},locale:'en-US'}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
let user=null,google=false,billing=false,billingPlan='starter',billingStatus=null,siteRows=[{id:'site-a',name:'First website',origin:'https://one.example.com',createdAt:Date.now()}],created=0,checkout,portalCalls=0,revenueRequests=[];
const plans=[{id:'free',name:'Free',monthlyPrice:0,yearlyPrice:0,currency:'USD',limits:{sites:1,monthlyEvents:10000}},{id:'starter',name:'Starter',monthlyPrice:9,yearlyPrice:90,currency:'USD',limits:{sites:3,monthlyEvents:100000}},{id:'growth',name:'Growth',monthlyPrice:29,yearlyPrice:290,currency:'USD',limits:{sites:10,monthlyEvents:1000000}}];
const respond=(route,data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname;
 if(path==='/api/auth/me')return respond(route,{user,billing:{plan:billingPlan,status:billingStatus||(billingPlan==='free'?'free':'active'),interval:'monthly',limits:plans[1].limits,usage:{month:'2026-09',events:4321}},capabilities:{google,billing}});
 if(path==='/api/plans')return respond(route,{plans,billingAvailable:billing});
 if(path==='/api/sites'){if(req.method()==='POST'){const body=req.postDataJSON();assert.equal(body.name,'Second website');assert.equal(body.origin,'https://two.example.com');created++;const site={id:'site-b',...body,createdAt:Date.now()};siteRows.push(site);return respond(route,{site},201);}return respond(route,{sites:siteRows});}
 if(path==='/api/billing/checkout'){checkout=req.postDataJSON();return respond(route,{error:'Billing test unavailable'},503);}
 if(path==='/api/billing/portal'){portalCalls++;return respond(route,{error:'Portal test unavailable'},503);}
 if(path==='/api/revenue'){revenueRequests.push({url:req.url(),authorization:req.headers().authorization});return respond(route,{overview:{visitors:0,sessions:0,customers:0,conversion:null,currencies:[]},stories:[],sources:[],journeys:[],dimensions:{},daily:[]});}
 if(path==='/api/auth/logout'){user=null;return respond(route,{ok:true});}
 return respond(route,{error:'unmocked'},404);
});
await mkdir('visual-review',{recursive:true});
try{
 await page.goto(base+'/account.html');await page.getByRole('heading',{name:'Your website has a story to tell.'}).waitFor();assert.equal(await page.locator('#googleSignIn').count(),0);assert.match(await page.locator('#accountContent').textContent(),/not configured/);
 google=true;await page.reload();await page.locator('#googleSignIn').waitFor();assert.equal(await page.locator('#googleSignIn').getAttribute('href'),'/api/auth/google');
 user={id:'user-test',name:'Test owner',email:'owner@example.com'};await page.reload();await page.locator('#installSnippet').waitFor();assert.match(await page.locator('#installSnippet').textContent(),/data-site="site-a"/);assert.match(await page.locator('#accountContent').textContent(),/4,321/);assert.match(await page.locator('#accountContent').textContent(),/collection not verified/);assert.equal(await page.locator('[data-checkout=growth]').isDisabled(),true);
 await page.locator('.create-site summary').click();await page.locator('input[name=name]').fill('Second website');await page.locator('input[name=origin]').fill('https://two.example.com/page');await page.getByRole('button',{name:'Create website',exact:true}).click();assert.equal(created,0);assert.match(await page.locator('#accountNotice').textContent(),/without a page path/);
 await page.locator('input[name=origin]').fill('https://two.example.com');await page.getByRole('button',{name:'Create website',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#installSnippet')?.textContent.includes('site-b'));assert.equal(created,1);assert.equal(await page.locator('[data-site-choice=site-b]').getAttribute('aria-pressed'),'true');
 await page.locator('[data-site-choice=site-a]').click();assert.match(await page.locator('#installSnippet').textContent(),/data-site="site-a"/);assert.ok(!(await page.locator('#installSnippet').textContent()).includes('token'));
 await page.goto(base+'/revenue.html');await page.locator('#accountSiteSelect:not([hidden])').waitFor();await page.locator('.dimension-grid').waitFor();assert.equal(await page.evaluate(()=>window.tideConnection.get().session),true);assert.equal(revenueRequests.at(-1).authorization,undefined);assert.equal(new URL(revenueRequests.at(-1).url).searchParams.get('site'),'site-a');
 await page.locator('#accountSiteSelect').selectOption('site-b');await page.waitForFunction(()=>document.querySelector('#accountSiteSelect').value==='site-b'&&document.querySelector('.dimension-grid'));assert.equal(new URL(revenueRequests.at(-1).url).searchParams.get('site'),'site-b');
 await page.locator('#accountSiteSelect').selectOption('site-a');await page.waitForFunction(()=>document.querySelector('.dimension-grid'));await page.goto(base+'/account.html');await page.locator('#installSnippet').waitFor();
 billing=true;billingPlan='free';await page.reload();await page.locator('[data-checkout=growth]').waitFor();await page.locator('[data-interval=yearly]').click();assert.match(await page.locator('.plans').textContent(),/\$290/);await page.locator('[data-checkout=growth]').click();await page.waitForFunction(()=>document.querySelector('#accountNotice').textContent.includes('Billing test unavailable'));assert.deepEqual(checkout,{plan:'growth',interval:'yearly'});assert.equal(await page.locator('[data-checkout=growth]').isDisabled(),false);
 billingPlan='starter';await page.reload();await page.locator('#billingPortal').waitFor();await page.locator('#billingPortal').click();await page.waitForFunction(()=>document.querySelector('#accountNotice').textContent.includes('Portal test unavailable'));assert.equal(portalCalls,1);
 billingPlan='free';billingStatus='past_due';await page.reload();await page.locator('[data-checkout=starter]').waitFor();await page.locator('[data-checkout=starter]').click();await page.waitForFunction(()=>document.querySelector('#accountNotice').textContent.includes('Portal test unavailable'));assert.equal(portalCalls,2,'past-due subscriptions must use the portal even when effective entitlement is free');billingPlan='starter';billingStatus=null;await page.reload();await page.locator('#installSnippet').waitFor();
 await page.screenshot({path:'visual-review/account-desktop.png',fullPage:true});
 await page.locator('[data-product-language]').selectOption('zh');if(await page.locator('[data-product-theme]').getAttribute('aria-checked')!=='false')await page.locator('[data-product-theme]').click();await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('#accountContent').textContent.includes('你的网站'));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'account mobile has no horizontal overflow');assert.equal(await page.locator('#installSnippet').getAttribute('data-no-translate'),null);assert.match(await page.locator('#installSnippet').textContent(),/data-site="site-a"/);await page.screenshot({path:'visual-review/account-zh-light-mobile.png',fullPage:true});
 await page.locator('#signOut').click();await page.locator('#googleSignIn').waitFor();assert.equal(await page.locator('#installSnippet').count(),0);assert.equal(await page.locator('[data-site-choice]').count(),0);assert.deepEqual(errors,[]);
 console.log('Account UI passed: auth/config states, site create/switch, validated origin, usage, billing error recovery, private snippet, i18n/theme/mobile, sign-out clearing.');
}finally{await browser.close();}
