import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {generateKeyPairSync,sign,createHmac} from 'node:crypto';
import {handleAccountRequest,getSessionUser,hashToken,canReadSite,getManagedSite,consumeEventQuota} from '../accounts.js';
const origin='https://tide.test';
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../migrations/0003_accounts.sql',import.meta.url),'utf8'));const db={prepare(query){return {bind(...args){return {first:async()=>sql.prepare(query).get(...args)||null,all:async()=>({results:sql.prepare(query).all(...args)}),run:async()=>sql.prepare(query).run(...args)};}}},async batch(statements){sql.exec('BEGIN');try{const values=[];for(const statement of statements)values.push(await statement.run());sql.exec('COMMIT');return values;}catch(e){sql.exec('ROLLBACK');throw e;}}};return {sql,db};}
const request=(path,method='GET',body,headers={})=>new Request(origin+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});
async function signedUser(db,id='user1'){await db.prepare('INSERT INTO account_users VALUES (?,?,?,?,?)').bind(id,'google-'+id,`${id}@example.test`,id,Date.now()).run();const token=Buffer.alloc(32,id==='user1'?1:2).toString('base64url');await db.prepare('INSERT INTO account_sessions VALUES (?,?,?)').bind(await hashToken(token),id,Date.now()+60000).run();return {'cookie':`__Host-tidestat_session=${token}`,origin};}
const billingEnv={APP_ORIGIN:origin,STRIPE_SECRET_KEY:'sk_test_secret',BILLING_WEBHOOK_SECRET:'whsec_billing',STRIPE_PRICE_STARTER_MONTHLY:'price_sm',STRIPE_PRICE_STARTER_YEARLY:'price_sy',STRIPE_PRICE_GROWTH_MONTHLY:'price_gm',STRIPE_PRICE_GROWTH_YEARLY:'price_gy'};
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}),jwk={...publicKey.export({format:'jwk'}),kid:'google-key',alg:'RS256'};
function jwt(claims){const head=Buffer.from(JSON.stringify({alg:'RS256',kid:'google-key'})).toString('base64url'),body=Buffer.from(JSON.stringify(claims)).toString('base64url'),content=`${head}.${body}`;return `${content}.${sign('RSA-SHA256',Buffer.from(content),privateKey).toString('base64url')}`;}
async function oauthFixture(overrides={},profileOverrides={}){const {db,sql}=database(),env={DB:db,APP_ORIGIN:origin,GOOGLE_CLIENT_ID:'google-client',GOOGLE_CLIENT_SECRET:'server-secret'};let nonce,capturedVerifier;
 env.FETCH=async(url,options={})=>{if(url.includes('/token')){capturedVerifier=new URLSearchParams(options.body).get('code_verifier');return Response.json({access_token:'access',id_token:jwt({iss:'https://accounts.google.com',aud:'google-client',sub:'google-sub',email:'verified@example.test',email_verified:true,nonce,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+300,...overrides})});}if(url.includes('/certs'))return Response.json({keys:[jwk]});if(url.includes('/userinfo'))return Response.json({sub:'google-sub',email:'verified@example.test',email_verified:true,name:'Verified User',...profileOverrides});throw Error('Unexpected network');};
 const started=await handleAccountRequest(request('/api/auth/google'),env),auth=new URL(started.headers.get('location'));nonce=auth.searchParams.get('nonce');const cookie=started.headers.get('set-cookie').split(';')[0],state=auth.searchParams.get('state');
 return {db,sql,env,auth,cookie,state,verifier:()=>capturedVerifier};}
test('Google code flow verifies signature/audience/nonce and profile before hashed secure session',async()=>{const f=await oauthFixture();assert.equal(f.auth.searchParams.get('code_challenge_method'),'S256');const callback=request(`/api/auth/callback?code=server-code&state=${f.state}`,'GET',null,{cookie:f.cookie});const response=await handleAccountRequest(callback,f.env);assert.equal(response.status,302);assert.equal(response.headers.get('location'),origin+'/account.html');assert.equal(await hashToken(f.verifier()),f.auth.searchParams.get('code_challenge'));const cookies=response.headers.getSetCookie();assert.match(cookies.find(c=>c.startsWith('__Host-tidestat_session=')),/HttpOnly; Secure; SameSite=Lax/);const session=cookies.find(c=>c.startsWith('__Host-tidestat_session=')).split(';')[0],user=await getSessionUser(request('/api/auth/me','GET',null,{cookie:session}),f.env);assert.equal(user.email,'verified@example.test');assert.equal(f.sql.prepare('SELECT token_hash FROM account_sessions').get().token_hash.includes(session.split('=')[1]),false);assert.equal((await handleAccountRequest(callback,f.env)).status,400);});
test('OAuth browser binding and trusted token audience prevent account injection',async()=>{const f=await oauthFixture();assert.equal((await handleAccountRequest(request(`/api/auth/callback?code=code&state=${f.state}`,'GET',null,{cookie:'__Host-tidestat_oauth=attacker'}),f.env)).status,400);const bad=await oauthFixture({aud:'other-client'});assert.equal((await handleAccountRequest(request(`/api/auth/callback?code=code&state=${bad.state}`,'GET',null,{cookie:bad.cookie}),bad.env)).status,400);assert.equal(bad.sql.prepare('SELECT COUNT(*) n FROM account_users').get().n,0);});
test('sites and sessions enforce user ownership and CSRF; free site allowance is enforced',async()=>{const {db}=database(),a=await signedUser(db),b=await signedUser(db,'user2'),env={DB:db,APP_ORIGIN:origin};assert.equal((await handleAccountRequest(request('/api/sites','POST',{name:'Site',origin:'https://site.test'},{cookie:a.cookie,origin:'https://evil.test'}),env)).status,403);const created=await handleAccountRequest(request('/api/sites','POST',{name:'Site',origin:'https://site.test'},a),env);assert.equal(created.status,201);const {site}=await created.json();assert.equal(await canReadSite(request('/','GET',null,a),env,site.id),true);assert.equal(await canReadSite(request('/','GET',null,b),env,site.id),false);assert.equal((await getManagedSite(db,site.id)).origin,'https://site.test');assert.equal((await handleAccountRequest(request('/api/sites','POST',{name:'Second',origin:'https://two.test'},a),env)).status,409);assert.deepEqual((await (await handleAccountRequest(request('/api/sites','GET',null,b),env)).json()).sites,[]);assert.equal((await handleAccountRequest(request('/api/auth/logout','POST',{},a),env)).status,200);assert.equal(await getSessionUser(request('/','GET',null,a),env),null);});
test('monthly quota is atomic/idempotent and calendar UTC scoped',async()=>{const {db}=database();await signedUser(db);await db.prepare('INSERT INTO account_sites VALUES (?,?,?,?,?)').bind('site1','user1','Site','https://site.test',Date.now()).run();const env={DB:db},month=new Date().toISOString().slice(0,7);await db.prepare('INSERT INTO account_usage VALUES (?,?,?)').bind('user1',month,9999).run();assert.equal((await consumeEventQuota(env,'site1','last')).allowed,true);assert.equal((await consumeEventQuota(env,'site1','last')).used,10000);assert.equal((await consumeEventQuota(env,'site1','over')).allowed,false);assert.equal((await consumeEventQuota(env,'legacy','event')).managed,false);});
test('billing checkout chooses configured price only and redirect grants no entitlement',async()=>{const {db}=database(),headers=await signedUser(db),calls=[],env={DB:db,...billingEnv,FETCH:async(url,opts)=>{calls.push([url,new URLSearchParams(opts?.body)]);if(url.includes('/prices/'))return Response.json({id:'price_sy',active:true,currency:'usd',unit_amount:9000,recurring:{interval:'year',interval_count:1,usage_type:'licensed'},billing_scheme:'per_unit'});if(url.endsWith('/customers'))return Response.json({id:'cus_user1'});if(url.endsWith('/checkout/sessions'))return Response.json({id:'cs_checkout',url:'https://checkout.stripe.com/example'});throw Error('unexpected');}};assert.equal((await handleAccountRequest(request('/api/billing/checkout','POST',{plan:'enterprise',interval:'monthly',price:'price_fake'},headers),env)).status,400);const result=await handleAccountRequest(request('/api/billing/checkout','POST',{plan:'starter',interval:'yearly',price:'price_fake'},headers),env);assert.equal(result.status,200);assert.equal(calls.at(-1)[1].get('line_items[0][price]'),'price_sy');const me=await (await handleAccountRequest(request('/api/auth/me?billing=success','GET',null,headers),env)).json();assert.equal(me.billing.plan,'free');assert.equal(JSON.stringify(me).includes('sk_test_secret'),false);});
function hook(event,secret='whsec_billing'){const raw=JSON.stringify(event),t=Math.floor(Date.now()/1000),signature=createHmac('sha256',secret).update(`${t}.${raw}`).digest('hex');return new Request(origin+'/api/billing/webhook',{method:'POST',headers:{'stripe-signature':`t=${t},v1=${signature}`},body:raw});}
test('billing webhook verifies separate signature, refetches subscription, dedupes and ignores stale state',async()=>{const {db}=database(),headers=await signedUser(db);await db.prepare('INSERT INTO account_billing(user_id,customer_id) VALUES (?,?)').bind('user1','cus_user1').run();let current={id:'sub1',customer:'cus_user1',created:100,status:'active',items:{data:[{price:{id:'price_sm'}}]}};const env={DB:db,...billingEnv,FETCH:async()=>Response.json(current)},event={id:'evt1',created:200,type:'customer.subscription.updated',data:{object:{id:'sub1',status:'canceled'}}};assert.equal((await handleAccountRequest(hook(event,'merchant-secret'),env)).status,401);assert.equal((await handleAccountRequest(hook(event),env)).status,200);let me=await (await handleAccountRequest(request('/api/auth/me','GET',null,headers),env)).json();assert.equal(me.billing.plan,'starter');assert.equal((await (await handleAccountRequest(hook(event),env)).json()).duplicate,true);current={...current,status:'canceled'};await handleAccountRequest(hook({...event,id:'evt2',created:300}),env);current={...current,status:'active'};await handleAccountRequest(hook({...event,id:'old',created:250}),env);me=await (await handleAccountRequest(request('/api/auth/me','GET',null,headers),env)).json();assert.equal(me.billing.plan,'free');});
test('missing external configuration is honestly unavailable and migration repeatable',async()=>{const {db,sql}=database(),env={DB:db,APP_ORIGIN:origin};sql.exec(readFileSync(new URL('../migrations/0003_accounts.sql',import.meta.url),'utf8'));assert.equal((await handleAccountRequest(request('/api/auth/google'),env)).status,503);const me=await (await handleAccountRequest(request('/api/auth/me'),env)).json();assert.equal(me.user,null);assert.equal(me.capabilities.google,false);const plans=await (await handleAccountRequest(request('/api/plans'),env)).json();assert.equal(plans.billingAvailable,false);assert.equal(plans.plans[2].limits.monthlyEvents,1000000);});
test('admin seeded claims are assigned only to the verified Google email, never submitted email',async()=>{const f=await oauthFixture();await f.db.prepare('INSERT INTO account_site_claims VALUES (?,?,?,?,?)').bind('claimed','VERIFIED@example.test','Trusted site','https://trusted.test',Date.now()).run();await f.db.prepare('INSERT INTO account_site_claims VALUES (?,?,?,?,?)').bind('other','another@example.test','Other','https://other.test',Date.now()).run();const response=await handleAccountRequest(request(`/api/auth/callback?code=code&state=${f.state}&email=another@example.test`,'GET',null,{cookie:f.cookie}),f.env);assert.equal(response.status,302);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM account_sites WHERE id='claimed'").get().n,1);assert.equal(f.sql.prepare("SELECT COUNT(*) n FROM account_sites WHERE id='other'").get().n,0);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM account_site_claims').get().n,1);});
test('pending checkout reuses the provider session and rejects concurrent different-plan purchases',async()=>{const {db}=database(),headers=await signedUser(db);let created=0;const env={DB:db,...billingEnv,FETCH:async(url,opts)=>{if(url.includes('/prices/'))return Response.json({active:true,currency:'usd',unit_amount:url.endsWith('price_gm')?2900:900,recurring:{interval:'month',interval_count:1,usage_type:'licensed'},billing_scheme:'per_unit'});if(url.endsWith('/customers'))return Response.json({id:'cus_pending'});if(url.endsWith('/checkout/sessions')){created++;return Response.json({id:'cs_pending',url:'https://checkout.stripe.com/pending',expires_at:Math.floor(Date.now()/1000)+3600});}if(url.endsWith('/checkout/sessions/cs_pending'))return Response.json({id:'cs_pending',url:'https://checkout.stripe.com/pending',status:'open',expires_at:Math.floor(Date.now()/1000)+3600});throw Error('unexpected');}};const call=plan=>handleAccountRequest(request('/api/billing/checkout','POST',{plan,interval:'monthly'},headers),env);assert.equal((await call('starter')).status,200);assert.equal((await call('starter')).status,200);assert.equal(created,1);assert.equal((await call('growth')).status,409);});
test('unverified Google profile or expired identity token cannot establish a session',async()=>{for(const f of [await oauthFixture({}, {email_verified:false}),await oauthFixture({exp:1}),await oauthFixture({nonce:'wrong-nonce'})]){const result=await handleAccountRequest(request(`/api/auth/callback?code=code&state=${f.state}`,'GET',null,{cookie:f.cookie}),f.env);assert.equal(result.status,400);assert.equal(f.sql.prepare('SELECT COUNT(*) n FROM account_sessions').get().n,0);}});
test('expired sessions are rejected and cross-origin logout cannot revoke an active session',async()=>{const {db}=database(),headers=await signedUser(db),env={DB:db,APP_ORIGIN:origin};assert.equal((await handleAccountRequest(request('/api/auth/logout','POST',{}, {...headers,origin:'https://evil.test'}),env)).status,403);assert.ok(await getSessionUser(request('/','GET',null,headers),env));await db.prepare('UPDATE account_sessions SET expires_at=?').bind(Date.now()-1).run();assert.equal(await getSessionUser(request('/','GET',null,headers),env),null);});
test('checkout fails closed when provider price amount, currency or interval differs from advertised plan',async()=>{
 for(const mismatch of [{unit_amount:999},{currency:'eur'},{recurring:{interval:'year',interval_count:1}},{recurring:{interval:'month',interval_count:2}},{active:false}]){
  const {db}=database(),headers=await signedUser(db);let created=false;
  const env={DB:db,...billingEnv,FETCH:async(url,options)=>{assert.ok(options.signal instanceof AbortSignal);if(url.includes('/prices/'))return Response.json({active:true,currency:'usd',unit_amount:900,recurring:{interval:'month',interval_count:1,usage_type:'licensed'},billing_scheme:'per_unit',...mismatch});created=true;throw Error('Must not create checkout');}};
  const result=await handleAccountRequest(request('/api/billing/checkout','POST',{plan:'starter',interval:'monthly'},headers),env);assert.equal(result.status,503);assert.equal(created,false);
 }
});

test('setup verification uses the owning account session and rejects another account',async()=>{
 const {db,sql}=database();sql.exec(readFileSync(new URL('../schema.sql',import.meta.url),'utf8'));
 const owner=await signedUser(db),other=await signedUser(db,'user2');
 await db.prepare('INSERT INTO account_sites VALUES (?,?,?,?,?)').bind('owned','user1','Owned website','https://shop.example',Date.now()).run();
 const {default:worker}=await import('../worker.js');
 const path='/api/setup?site=owned&origin=https%3A%2F%2Fshop.example&since='+Date.now();
 const accepted=await worker.fetch(request(path,'GET',undefined,owner),{DB:db,APP_ORIGIN:origin});assert.equal(accepted.status,200);const body=await accepted.json();assert.equal(body.originAllowed,true);assert.equal(body.pageviewReceived,false);
 assert.equal((await worker.fetch(request(path,'GET',undefined,other),{DB:db,APP_ORIGIN:origin})).status,401);
});
